build:
  cuda_version: "12.1.1"
  system_packages:
    - "ffmpeg"
    - "libsm6"
    - "libxext6"
    - "libssl-dev"
    - "libx11-6"
    - "libgl1-mesa-glx"
  run:
    - "git clone https://github.com/TencentARC/GFPGAN.git"
    - "cd GFPGAN"
    - "python3 setup.py develop"
    - "pip install basicsr==1.4.2"
    - "pip install facexlib==0.3.0"
    - "pip install -r requirements.txt"
    - "python3 setup.py develop"
    - "pip install realesrgan==0.3.0"
    - "pip install torchvision==0.16.0"
